package com.kegc.web;

public class UserController {
	public static void main(String[] args) {
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
	}
	
	public void fun1() {
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
	}
	
	public void fun2() {
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
	}
	public void fun3() {
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
	}
	public void fun4() {
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
	}
	public void fun5() {
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
	}
	public void fun6() {
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
		System.out.println("aaa");
		System.out.println("bbb");
		System.out.println("ccc");
	}
}
